### ISSUE TITLE
Verticality fails with `(setq resize-mini-windows t)`

### ISSUE THREAD

**Issue by protesilaos** [oantolin/icomplete-vertical#1] opened 2020-04-03 03:30 UTC
Thank you for making this library!

With `icomplete-vertical-mode` active, when I evaluate `(setq resize-mini-windows t)` and run a completion command, I get just a single line.  Whereas with `(setq resize-mini-windows 'grow-only)` I get the expect presentation. Screenshots:

![Screenshot at 2020-04-03 06-25-51](https://user-images.githubusercontent.com/12828033/78321250-1b209e00-7574-11ea-8a74-f6392846ba65.png)

![Screenshot at 2020-04-03 06-25-34](https://user-images.githubusercontent.com/12828033/78321246-165bea00-7574-11ea-9ee4-85decbc2989b.png)

I think the `t` value should be respected, since it allows the minibuffer to both grow and shrink depending on the number of candidates.

**Comment by protesilaos** [comment] 2020-04-03 03:52
This patch would address the issue. I can do a pull request, if you will, though I am not sure it is good to prevent the minibuffer from shrinking in size.  Maybe we need to research this further.

```diff
 icomplete-vertical.el | 9 ++++++++-
 1 file changed, 8 insertions(+), 1 deletion(-)

diff --git a/icomplete-vertical.el b/icomplete-vertical.el
index d35c89e..d4efc23 100644
--- a/icomplete-vertical.el
+++ b/icomplete-vertical.el
@@ -43,6 +43,11 @@ It is then restored when icomplete-vertical-mode is turned off.")
 Records the value when `icomplete-vertical-mode' is turned on.
 It is then restored when icomplete-vertical-mode is turned off.")
 
+(defvar icomplete-vertical-old-resize-mini-windows nil
+  "Store last known value of `resize-mini-windows'.
+Records the value when `icomplete-vertical-mode' is turned on.
+It is then restored when icomplete-vertical-mode is turned off.")
+
 (defun icomplete-vertical-format-completions (completions)
   "Reformat COMPLETIONS for better aesthetics.
 To be used as filter return advice for `icomplete-completions'."
@@ -70,7 +75,9 @@ Meant to be added to `icomplete-minibuffer-setup-hook'."
         (setq icomplete-vertical-old-separator icomplete-separator
               icomplete-separator "\n"
               icomplete-vertical-old-hide-common icomplete-hide-common-prefix
-              icomplete-hide-common-prefix nil)
+              icomplete-hide-common-prefix nil
+              icomplete-vertical-old-resize-mini-windows resize-mini-windows
+              resize-mini-windows 'grow-only)
         (advice-add 'icomplete-completions
                     :filter-return #'icomplete-vertical-format-completions)
         (add-hook 'icomplete-minibuffer-setup-hook
```

**Comment by oantolin** [comment] 2020-04-03 07:53
I think this one will be pretty tough. I believe the issue is basically caused by icomplete using an overlay to display the candidates. I'm not completely sure, but I think that the height of the overlay just doesn't count, so Emacs believes the entire text you want to put in the minibuffer is only one line tall. Thus, if the minibuffer is allowed to shrink, it does.

I'll think about it more, but I currently think this would require fairly substantial changes to fix. And I do want to keep the spirit of this package as just minor cosmetic changes on top of `icomplete`. So I'm tentatively in favor of this strategy of simply forcing `resize-mini-windows` to be `grow-only` while `icomplete-vertical-mode` is active, as in your patch.

Thanks again!

**Comment by oantolin** [comment] 2020-04-03 09:16
I don't know at the moment how to truly fix the issue, allowing the minibuffer to shrink, so for now I'm just merging your patch. Thanks again!

Actually I made one change on top of your patch: I thought that four `icomplete-vertical-old-*` variables was too many, so I consolidated all the necessary saved into a single variable. Just for tidyness.

**Comment by protesilaos** [comment] 2020-04-03 12:13
Yes, I figured as much. This is something that should be fixed in core Emacs.  We should at least offer a note in the README. I can write something if you want.

Noticed your addition: consolidating variables is the right thing to do.

**Comment by oantolin** [comment] 2020-04-03 15:06
I'm closing this issue, since the package now does something useful even no matter what the value of `resize-mini-windows` is (so I feel the title is addressed). I could open a new issue specifically about allowing the minibuffer to shrink, but I kind of don't want that hanging over my head.

**Closed by oantolin** 2020-04-03 15:06 UTC

**Comment by protesilaos** [comment] 2020-04-03 16:31
I agree. Thanks!
